name: Python PEP8 Lint

on:
  push:
    branches: [ main, master ] # Adjust if your main branch has a different name
  pull_request:
    branches: [ main, master ] # Adjust if your main branch has a different name

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x' # Use a specific version if needed, e.g., '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make install

    - name: Lint with autopep8 (via Makefile)
      run: make lint
